[tool.poetry]
name = "play-cursor"
version = "0.1.0"
description = ""
authors = ["armundl3 <armundle@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.7,<3.12"
fastapi = "0.115.12"
uvicorn = "0.34.2"
gradio = "5.29.0"
requests = "^2.32.3"
typer = {extras = ["all"], version = "^0.12.3"}
youtube-search-python = "^1.6.6"
beautifulsoup4 = "^4.13.4"
python-dotenv = "^1.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"

[tool.poetry.scripts]
play-cursor = "cli:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
